/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.ReporteDeVentas;

import AccesoADatos.ClienteData;
import static AccesoADatos.ClienteData.clientes;
import AccesoADatos.DetalleVentaData;
import AccesoADatos.ProductoData;
import AccesoADatos.VentaData;
import static AccesoADatos.VentaData.ventas;
import Entidades.Cliente;
import Entidades.DetalleVenta;
import Entidades.Producto;
import Entidades.Venta;
import static Vista.JfrMenu1.jDesktopPaneMenu;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gaming
 */
public class PorCliente extends javax.swing.JInternalFrame {

   DefaultTableModel modelo = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int f, int c) {
        return false;
    }
    };
    VentaData vData;
    DetalleVentaData dvData;
    ClienteData cData;
    ProductoData pData;
    DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    
   
   
    public PorCliente() throws SQLException {
        this.pData = new ProductoData();
        this.cData = new ClienteData();
        this.dvData = new DetalleVentaData();
        this.vData = new VentaData();
       
        initComponents();
        cabecera();
         cData.listaClientes(); 
         cargaCombo();
          
         
         
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jcbClientes = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tListaVentas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        VerDetalle = new javax.swing.JButton();
        EliminarV = new javax.swing.JButton();

        setClosable(true);
        setTitle("Ventas por cliente");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Seleccione cliente");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 25, -1, -1));

        jcbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbClientesActionPerformed(evt);
            }
        });
        jPanel1.add(jcbClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 20, 228, -1));

        tListaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tListaVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tListaVentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tListaVentas);
        if (tListaVentas.getColumnModel().getColumnCount() > 0) {
            tListaVentas.getColumnModel().getColumn(0).setResizable(false);
            tListaVentas.getColumnModel().getColumn(0).setPreferredWidth(50);
            tListaVentas.getColumnModel().getColumn(1).setResizable(false);
            tListaVentas.getColumnModel().getColumn(1).setPreferredWidth(50);
            tListaVentas.getColumnModel().getColumn(2).setPreferredWidth(330);
            tListaVentas.getColumnModel().getColumn(3).setResizable(false);
            tListaVentas.getColumnModel().getColumn(3).setPreferredWidth(79);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 64, 367, 164));

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 250, 90, 30));

        VerDetalle.setBackground(new java.awt.Color(204, 255, 255));
        VerDetalle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        VerDetalle.setText("Ver detalle");
        VerDetalle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        VerDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerDetalleActionPerformed(evt);
            }
        });
        jPanel1.add(VerDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 250, 90, 30));

        EliminarV.setBackground(new java.awt.Color(153, 0, 0));
        EliminarV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EliminarV.setForeground(new java.awt.Color(255, 255, 255));
        EliminarV.setText("Eliminar");
        EliminarV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EliminarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarVActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarV, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarVActionPerformed
        int idVenta= Integer.parseInt(tListaVentas.getValueAt(tListaVentas.getSelectedRow(),0).toString());
        vData.eliminarVenta(idVenta);
        borrarFilas();
        VentasPorCliente();
    }//GEN-LAST:event_EliminarVActionPerformed

    private void VerDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerDetalleActionPerformed

        int sel=tListaVentas.getSelectedRowCount();
        if (sel==1) {
            int id= Integer.parseInt(tListaVentas.getValueAt(tListaVentas.getSelectedRow(),0).toString());

            VerDetalle verDetalle = null;
            try {
                verDetalle = new VerDetalle(id);
            } catch (SQLException ex) {
                Logger.getLogger(PorCliente.class.getName()).log(Level.SEVERE, null, ex);
            }

            jDesktopPaneMenu.add(verDetalle);
            verDetalle.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(rootPane,"Seleccione solo una fila para ver su detalle");

        }

    }//GEN-LAST:event_VerDetalleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tListaVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tListaVentasMouseClicked
        VerDetalle.setEnabled(true);
    }//GEN-LAST:event_tListaVentasMouseClicked

    private void jcbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbClientesActionPerformed

        borrarFilas();
        VentasPorCliente();
        VerDetalle.setEnabled(false);

    }//GEN-LAST:event_jcbClientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarV;
    private javax.swing.JButton VerDetalle;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Cliente> jcbClientes;
    private javax.swing.JTable tListaVentas;
    // End of variables declaration//GEN-END:variables

private void cabecera() {
        modelo.addColumn("ID Venta");
        modelo.addColumn("Cantidad");
         modelo.addColumn("Nombre producto");
        modelo.addColumn("Fecha de venta");
        modelo.addColumn("ID Vendedor");
        
        

        tListaVentas.setModel(modelo);
    }

public void cargaCombo(){
    
    for (Cliente cliente : clientes) {
        jcbClientes.addItem(cliente);
    }
   
    clientes.clear();
}

    public void VentasPorCliente() {

        Cliente c = (Cliente) jcbClientes.getSelectedItem();
        
        vData.buscarVentasxCliente(c.getIdCliente());

        for (Venta venta : ventas) {
            DetalleVenta dv= dvData.detallarVenta(venta.getIdVenta());
            Producto prod = pData.buscarPorId(dv.getIdProducto());
             LocalDate fecha=venta.getFechaVenta();
            String fechaOk=fecha.format(dateTimeFormatter);
            modelo.addRow(new Object[]{
                venta.getIdVenta(),
                dv.getCantidad(),
                prod.getNombreProducto(),
                fechaOk,
                venta.getIdUsuario(),});

        }
        ventas.clear();
    }

    
public void borrarFilas(){
     int f = (tListaVentas.getRowCount() - 1);
        for (; f >= 0; f--) {
            modelo.removeRow(f);
        }
}


}
