/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.ReporteDeVentas;

import AccesoADatos.DetalleVentaData;
import AccesoADatos.ProductoData;
import AccesoADatos.UsuarioData;
import AccesoADatos.VentaData;
import static AccesoADatos.VentaData.ventas;
import Entidades.DetalleVenta;
import Entidades.Producto;
import Entidades.Venta;
import static Vista.JfrMenu1.jDesktopPaneMenu;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gaming
 */
public class PorFecha extends javax.swing.JInternalFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    UsuarioData uData = new UsuarioData();
    VentaData vData = new VentaData();
    DetalleVentaData dvData = new DetalleVentaData();
    ProductoData pData = new ProductoData();

    public PorFecha() {
        initComponents();
        cargaTodo();
        cabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tListaVentas = new javax.swing.JTable();
        Salir = new javax.swing.JButton();
        jcFecha = new com.toedter.calendar.JDateChooser();
        EliminarVenta = new javax.swing.JButton();
        VerDetalle = new javax.swing.JButton();

        setTitle("Ventas por fecha");
        setToolTipText("");

        jLabel2.setText("Seleccione fecha de venta");

        tListaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tListaVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tListaVentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tListaVentas);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        jcFecha.setDateFormatString("dd/MM/yyyy");
        jcFecha.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jcFechaPropertyChange(evt);
            }
        });

        EliminarVenta.setText("Eliminar");
        EliminarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarVentaActionPerformed(evt);
            }
        });

        VerDetalle.setText("Ver Detalle");
        VerDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerDetalleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(300, 300, 300)
                                .addComponent(EliminarVenta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(VerDetalle)
                                .addGap(14, 14, 14)
                                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salir)
                    .addComponent(EliminarVenta)
                    .addComponent(VerDetalle))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void jcFechaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jcFechaPropertyChange
        if (jcFecha.getDateFormatString() == null) {
            JOptionPane.showMessageDialog(rootPane, "Selecciona una fecha o ingrese una en formato yyyy/mm/dd");
            cargaTodo();
            VerDetalle.setEnabled(false);
        } else {
            try {
                borrarFilas();
                cargaTabla();
                VerDetalle.setEnabled(false);
            } catch (Exception e) {
                cargaTodo();
                VerDetalle.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jcFechaPropertyChange

    private void EliminarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarVentaActionPerformed
         int idVenta= Integer.parseInt(tListaVentas.getValueAt(tListaVentas.getSelectedRow(),0).toString());
        vData.eliminarVenta(idVenta);
        try {
            borrarFilas();
        cargaTabla();
        } catch (Exception e) {
        cargaTodo();}
    }//GEN-LAST:event_EliminarVentaActionPerformed

    private void VerDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerDetalleActionPerformed
        int sel=tListaVentas.getSelectedRowCount();
          if (sel==1) {
           int id= Integer.parseInt(tListaVentas.getValueAt(tListaVentas.getSelectedRow(),0).toString());
            
            
            VerDetalle verDetalle = new VerDetalle(id);

        
         jDesktopPaneMenu.add(verDetalle);
        verDetalle.setVisible(true); 
        }else{
              JOptionPane.showMessageDialog(rootPane,"Seleccione solo una fila para ver su detalle");
              
          }

    }//GEN-LAST:event_VerDetalleActionPerformed

    private void tListaVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tListaVentasMouseClicked
        VerDetalle.setEnabled(true);
    }//GEN-LAST:event_tListaVentasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarVenta;
    private javax.swing.JButton Salir;
    private javax.swing.JButton VerDetalle;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jcFecha;
    private javax.swing.JTable tListaVentas;
    // End of variables declaration//GEN-END:variables

    public void cabecera() {
        modelo.addColumn("id Venta");
        modelo.addColumn("idCliente");
        modelo.addColumn("Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("id Usuario");
        modelo.addColumn("Fecha venta");
        tListaVentas.setModel(modelo);
    }

    public void cargaTabla() {
        int año = 0, mes = -1, dia = 0;
        año = jcFecha.getCalendar().get(Calendar.YEAR);
        mes = jcFecha.getCalendar().get(Calendar.MARCH);
        dia = jcFecha.getCalendar().get(Calendar.DAY_OF_MONTH);
        LocalDate fecha = LocalDate.of(año, (mes + 1), dia);

String fechaOk = fecha.format(dateTimeFormatter);  //17-02-2022
        if (año != 0 && mes != -1 && dia != 0) {
            vData.buscarVentasxFecha(fecha);

            for (Venta venta : ventas) {
                DetalleVenta dv = dvData.detallarVenta(venta.getIdVenta());
                Producto prod = pData.buscarPorId(dv.getIdProducto());
                modelo.addRow(new Object[]{
                    venta.getIdVenta(),
                    venta.getIdCliente(),
                    prod.getNombreProducto(),
                    dv.getCantidad(),
                    venta.getIdUsuario(),
                    fechaOk
                });
            }
        }
        ventas.clear();

    }

    public void cargaTodo() {
        vData.listarVentas();

String fechaOk;
        for (Venta venta : ventas) {
            DetalleVenta dv = dvData.detallarVenta(venta.getIdVenta());
            Producto prod = pData.buscarPorId(dv.getIdProducto());
            LocalDate fecha=venta.getFechaVenta();
            fechaOk=fecha.format(dateTimeFormatter);
            modelo.addRow(new Object[]{
                venta.getIdVenta(),
                venta.getIdCliente(),
                prod.getNombreProducto(),
                dv.getCantidad(),
                venta.getIdUsuario(),
                 fechaOk
               
            });
        }
        ventas.clear();
    }

    public void borrarFilas() {
        int f = (tListaVentas.getRowCount() - 1);
        for (; f >= 0; f--) {
            modelo.removeRow(f);
        }
    }

}
