/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.ReporteDeVentas;

import AccesoADatos.DetalleVentaData;
import AccesoADatos.ProductoData;
import AccesoADatos.UsuarioData;
import AccesoADatos.VentaData;
import static AccesoADatos.VentaData.ventas;
import Entidades.DetalleVenta;
import Entidades.Producto;
import Entidades.Venta;
import static Vista.JfrMenu1.jDesktopPaneMenu;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gaming
 */
public class PorFecha extends javax.swing.JInternalFrame {

    DefaultTableModel modelo = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int f, int c) {
        return false;
    }
    };
    DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    UsuarioData uData;
    VentaData vData;
    DetalleVentaData dvData;
    ProductoData pData;

    public PorFecha() throws SQLException {
        this.pData = new ProductoData();
        this.dvData = new DetalleVentaData();
        this.vData = new VentaData();
        this.uData = new UsuarioData();
        initComponents();
        cargaTodo();
        cabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tListaVentas = new javax.swing.JTable();
        Salir = new javax.swing.JButton();
        jcFecha = new com.toedter.calendar.JDateChooser();
        EliminarVenta = new javax.swing.JButton();
        VerDetalle = new javax.swing.JButton();

        setClosable(true);
        setTitle("Ventas por fecha");
        setToolTipText("");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(69, 99, 99));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Seleccione fecha de venta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 31, -1, -1));

        tListaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tListaVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tListaVentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tListaVentas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 78, 583, 187));

        Salir.setBackground(new java.awt.Color(153, 0, 0));
        Salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 90, 30));

        jcFecha.setDateFormatString("dd/MM/yyyy");
        jcFecha.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jcFechaPropertyChange(evt);
            }
        });
        jPanel1.add(jcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 19, 292, -1));

        EliminarVenta.setBackground(new java.awt.Color(153, 0, 0));
        EliminarVenta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EliminarVenta.setForeground(new java.awt.Color(255, 255, 255));
        EliminarVenta.setText("Eliminar");
        EliminarVenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EliminarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarVentaActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 90, 30));

        VerDetalle.setBackground(new java.awt.Color(153, 255, 255));
        VerDetalle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        VerDetalle.setText("Ver Detalle");
        VerDetalle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        VerDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerDetalleActionPerformed(evt);
            }
        });
        jPanel1.add(VerDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 290, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 342));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void jcFechaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jcFechaPropertyChange
        if (jcFecha.getDateFormatString() == null) {
            JOptionPane.showMessageDialog(rootPane, "Selecciona una fecha o ingrese una en formato yyyy/mm/dd");
            cargaTodo();
            VerDetalle.setEnabled(false);
        } else {
            try {
                borrarFilas();
                cargaTabla();
                VerDetalle.setEnabled(false);
            } catch (Exception e) {
                cargaTodo();
                VerDetalle.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jcFechaPropertyChange

    private void EliminarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarVentaActionPerformed
         int idVenta= Integer.parseInt(tListaVentas.getValueAt(tListaVentas.getSelectedRow(),0).toString());
        vData.eliminarVenta(idVenta);
        try {
            borrarFilas();
        cargaTabla();
        } catch (Exception e) {
        cargaTodo();}
    }//GEN-LAST:event_EliminarVentaActionPerformed

    private void VerDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerDetalleActionPerformed
        int sel=tListaVentas.getSelectedRowCount();
          if (sel==1) {
           int id= Integer.parseInt(tListaVentas.getValueAt(tListaVentas.getSelectedRow(),0).toString());
            
            
            VerDetalle verDetalle = null;
            try {
                verDetalle = new VerDetalle(id);
            } catch (SQLException ex) {
                Logger.getLogger(PorFecha.class.getName()).log(Level.SEVERE, null, ex);
            }

        
         jDesktopPaneMenu.add(verDetalle);
        verDetalle.setVisible(true); 
        }else{
              JOptionPane.showMessageDialog(rootPane,"Seleccione solo una fila para ver su detalle");
              
          }

    }//GEN-LAST:event_VerDetalleActionPerformed

    private void tListaVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tListaVentasMouseClicked
        VerDetalle.setEnabled(true);
    }//GEN-LAST:event_tListaVentasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarVenta;
    private javax.swing.JButton Salir;
    private javax.swing.JButton VerDetalle;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jcFecha;
    private javax.swing.JTable tListaVentas;
    // End of variables declaration//GEN-END:variables

    public void cabecera() {
        modelo.addColumn("id Venta");
        modelo.addColumn("idCliente");
        modelo.addColumn("Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("id Usuario");
        modelo.addColumn("Fecha venta");
        tListaVentas.setModel(modelo);
    }

    public void cargaTabla() {
        int año = 0, mes = -1, dia = 0;
        año = jcFecha.getCalendar().get(Calendar.YEAR);
        mes = jcFecha.getCalendar().get(Calendar.MARCH);
        dia = jcFecha.getCalendar().get(Calendar.DAY_OF_MONTH);
        LocalDate fecha = LocalDate.of(año, (mes + 1), dia);

String fechaOk = fecha.format(dateTimeFormatter);  //17-02-2022
        if (año != 0 && mes != -1 && dia != 0) {
            vData.buscarVentasxFecha(fecha);

            for (Venta venta : ventas) {
                DetalleVenta dv = dvData.detallarVenta(venta.getIdVenta());
                Producto prod = pData.buscarPorId(dv.getIdProducto());
                modelo.addRow(new Object[]{
                    venta.getIdVenta(),
                    venta.getIdCliente(),
                    prod.getNombreProducto(),
                    dv.getCantidad(),
                    venta.getIdUsuario(),
                    fechaOk
                });
            }
        }
        ventas.clear();

    }

    public void cargaTodo() {
        vData.listarVentas();

String fechaOk;
        for (Venta venta : ventas) {
            DetalleVenta dv = dvData.detallarVenta(venta.getIdVenta());
            Producto prod = pData.buscarPorId(dv.getIdProducto());
            LocalDate fecha=venta.getFechaVenta();
            fechaOk=fecha.format(dateTimeFormatter);
            modelo.addRow(new Object[]{
                venta.getIdVenta(),
                venta.getIdCliente(),
                prod.getNombreProducto(),
                dv.getCantidad(),
                venta.getIdUsuario(),
                 fechaOk
               
            });
        }
        ventas.clear();
    }

    public void borrarFilas() {
        int f = (tListaVentas.getRowCount() - 1);
        for (; f >= 0; f--) {
            modelo.removeRow(f);
        }
    }

}
