/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.ReporteDeVentas;

import AccesoADatos.ClienteData;
import AccesoADatos.DetalleVentaData;
import AccesoADatos.ProductoData;
import static AccesoADatos.ProductoData.productos;
import AccesoADatos.VentaData;
import static AccesoADatos.VentaData.ventas;
import Entidades.Cliente;
import Entidades.DetalleVenta;
import Entidades.Producto;
import Entidades.Venta;
import static Vista.JfrMenu1.jDesktopPaneMenu;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gaming
 */
public class PorProducto extends javax.swing.JInternalFrame {

    DefaultTableModel modelo = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int f, int c) {
        return false;
    }
    };
    VentaData vData;
    DetalleVentaData dvData;
    ProductoData pData;
    ClienteData cData;
    DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    public PorProducto() throws SQLException {
        this.cData = new ClienteData();
        this.pData = new ProductoData();
        this.dvData = new DetalleVentaData();
        this.vData = new VentaData();
        initComponents(); 
        cabecera();
        pData.listarProductos();
        CargaCombo();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bEliminarVenta = new javax.swing.JButton();
        VerDetalle = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jcbProductos = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tListaVentas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Ventas por producto");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(26, 43, 61));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bEliminarVenta.setText("Eliminar");
        bEliminarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarVentaActionPerformed(evt);
            }
        });
        jPanel1.add(bEliminarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 229, -1, -1));

        VerDetalle.setText("Ver Detalle");
        VerDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerDetalleActionPerformed(evt);
            }
        });
        jPanel1.add(VerDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 229, -1, -1));

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });
        jPanel1.add(bSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 229, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Seleccione producto:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 145, 20));

        jcbProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbProductosActionPerformed(evt);
            }
        });
        jPanel1.add(jcbProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 18, 302, -1));

        tListaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tListaVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tListaVentasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tListaVentas);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 57, -1, 154));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 270));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 267, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_bSalirActionPerformed

    private void jcbProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbProductosActionPerformed
       
        borrarFilas();
        CargaTablaxProd();
         VerDetalle.setEnabled(false);
        
    }//GEN-LAST:event_jcbProductosActionPerformed

    private void bEliminarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarVentaActionPerformed
         int idVenta= Integer.parseInt(tListaVentas.getValueAt(tListaVentas.getSelectedRow(),0).toString());
        vData.eliminarVenta(idVenta);
         borrarFilas();
        CargaTablaxProd();
        VerDetalle.setEnabled(false);
    }//GEN-LAST:event_bEliminarVentaActionPerformed

    private void VerDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerDetalleActionPerformed
         int sel=tListaVentas.getSelectedRowCount();
          if (sel==1) {
           int id= Integer.parseInt(tListaVentas.getValueAt(tListaVentas.getSelectedRow(),0).toString());
            
            
            VerDetalle verDetalle = null;
             try {
                 verDetalle = new VerDetalle(id);
             } catch (SQLException ex) {
                 Logger.getLogger(PorProducto.class.getName()).log(Level.SEVERE, null, ex);
             }

        
         jDesktopPaneMenu.add(verDetalle);
        verDetalle.setVisible(true); 
        }else{
              JOptionPane.showMessageDialog(rootPane,"Seleccione solo una fila para ver su detalle");
              
          }
 
    }//GEN-LAST:event_VerDetalleActionPerformed

    private void tListaVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tListaVentasMouseClicked
        VerDetalle.setEnabled(true);
    }//GEN-LAST:event_tListaVentasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VerDetalle;
    private javax.swing.JButton bEliminarVenta;
    private javax.swing.JButton bSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<Producto> jcbProductos;
    private javax.swing.JTable tListaVentas;
    // End of variables declaration//GEN-END:variables

    public void cabecera() {
        modelo.addColumn("id Venta"); 
        modelo.addColumn("Cantidad");
        modelo.addColumn("Nombre Cliente");
        modelo.addColumn("id Cliente");
        modelo.addColumn("Fecha de venta");

        tListaVentas.setModel(modelo);
    }

    

    public void CargaCombo() {

        for (Producto producto : productos) {
            jcbProductos.addItem(producto);
        }
        
        productos.clear();

    }

    public void CargaTablaxProd() {
        Producto prod = (Producto) jcbProductos.getSelectedItem();
        int id=prod.getIdProducto();
        vData.porProducto(id);

        for (Venta venta : ventas) {
            DetalleVenta dv= dvData.detallarVenta(venta.getIdVenta());
            Cliente c=cData.buscarClienteXid(venta.getIdCliente());
           LocalDate fecha=venta.getFechaVenta();
            String fechaOk=fecha.format(dateTimeFormatter);
                modelo.addRow(new Object[]{
                    venta.getIdVenta(),
                    dv.getCantidad(),
                     c.getApellido()+" "+c.getNombre(),
                    venta.getIdCliente(),
                    fechaOk
                });
        }

        ventas.clear();
    }

    public void borrarFilas() {
        int f = (tListaVentas.getRowCount() -1);
       for (; f >=0; f--) {
            modelo.removeRow(f);
        }
    }

}
