/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.ReporteDeVentas;

import AccesoADatos.ClienteData;
import AccesoADatos.DetalleVentaData;
import AccesoADatos.ProductoData;
import static AccesoADatos.ProductoData.productos;
import AccesoADatos.VentaData;
import static AccesoADatos.VentaData.ventas;
import Entidades.Cliente;
import Entidades.DetalleVenta;
import Entidades.Producto;
import Entidades.Venta;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gaming
 */
public class PorProducto extends javax.swing.JInternalFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    VentaData vData = new VentaData();
    DetalleVentaData dvData = new DetalleVentaData();
    ProductoData pData = new ProductoData();
    ClienteData cData = new ClienteData();

    public PorProducto() {
        initComponents(); 
        cabecera();
        pData.listarProductos();
        CargaCombo();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bEliminarVenta = new javax.swing.JButton();
        bVerDetalle = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jcbProductos = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tListaVentas = new javax.swing.JTable();

        setTitle("Ventas por producto");

        bEliminarVenta.setText("Eliminar");

        bVerDetalle.setText("Ver Detalle");

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        jLabel2.setText("Seleccione producto");

        jcbProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbProductosActionPerformed(evt);
            }
        });

        tListaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tListaVentas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jcbProductos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(bEliminarVenta)
                                .addGap(38, 38, 38)
                                .addComponent(bVerDetalle)
                                .addGap(57, 57, 57)
                                .addComponent(bSalir)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEliminarVenta)
                    .addComponent(bVerDetalle)
                    .addComponent(bSalir))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_bSalirActionPerformed

    private void jcbProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbProductosActionPerformed
       
        borrarFilas();
        CargaTablaxProd();
        
    }//GEN-LAST:event_jcbProductosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEliminarVenta;
    private javax.swing.JButton bSalir;
    private javax.swing.JButton bVerDetalle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<Producto> jcbProductos;
    private javax.swing.JTable tListaVentas;
    // End of variables declaration//GEN-END:variables

    public void cabecera() {
        modelo.addColumn("id Venta"); 
        modelo.addColumn("Cantidad");
        modelo.addColumn("Nombre Cliente");
        modelo.addColumn("id Cliente");
        modelo.addColumn("Fecha de venta");

        tListaVentas.setModel(modelo);
    }

    

    public void CargaCombo() {

        for (Producto producto : productos) {
            jcbProductos.addItem(producto);
        }
        
        productos.clear();

    }

    public void CargaTablaxProd() {
        Producto prod = (Producto) jcbProductos.getSelectedItem();
        int id=prod.getIdProducto();
        vData.porProducto(id);

        for (Venta venta : ventas) {
            DetalleVenta dv= dvData.detallarVenta(venta.getIdVenta());
           Cliente c=cData.buscarCliente(venta.getIdCliente());
           
                modelo.addRow(new Object[]{
                    venta.getIdVenta(),
                    dv.getCantidad(),
                     c.getApellido()+" "+c.getNombre(),
                    venta.getIdCliente(),
                    venta.getFechaVenta(),
                });
        }

        ventas.clear();
    }

    public void borrarFilas() {
        int f = (tListaVentas.getRowCount() -1);
       for (; f >=0; f--) {
            modelo.removeRow(f);
        }
    }

}
