/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.ReporteDeVentas;

import AccesoADatos.DetalleVentaData;
import AccesoADatos.ProductoData;
import AccesoADatos.UsuarioData;
import static AccesoADatos.UsuarioData.usuarios;
import AccesoADatos.VentaData;
import static AccesoADatos.VentaData.ventas;
import Entidades.DetalleVenta;
import Entidades.Producto;
import Entidades.Usuario;
import Entidades.Venta;
import static Vista.JfrMenu1.jDesktopPaneMenu;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gaming
 */
public class PorUsuario extends javax.swing.JInternalFrame {

    DefaultTableModel modelo = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int f, int c) {
        return false;
    }
    };
    UsuarioData uData;
    VentaData vData;
    DetalleVentaData dvData;
    ProductoData pData;
    DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    
    public PorUsuario() throws SQLException {
        this.pData = new ProductoData();
        this.dvData = new DetalleVentaData();
        this.vData = new VentaData();
        this.uData = new UsuarioData();
        initComponents();
        cabecera();
        uData.listarUsuarios();
        cargaCombo();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jcbUsuarios = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tListaVentas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        EliminarVenta = new javax.swing.JButton();
        VerDetalle = new javax.swing.JButton();

        setClosable(true);
        setTitle("Ventas por usuario");

        jPanel1.setBackground(new java.awt.Color(94, 45, 45));

        jLabel2.setText("Seleccione un usuario");

        jcbUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbUsuariosActionPerformed(evt);
            }
        });

        tListaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Nombre producto", "Fecha venta"
            }
        ));
        tListaVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tListaVentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tListaVentas);
        if (tListaVentas.getColumnModel().getColumnCount() > 0) {
            tListaVentas.getColumnModel().getColumn(0).setResizable(false);
            tListaVentas.getColumnModel().getColumn(0).setPreferredWidth(50);
            tListaVentas.getColumnModel().getColumn(1).setResizable(false);
            tListaVentas.getColumnModel().getColumn(1).setPreferredWidth(50);
            tListaVentas.getColumnModel().getColumn(2).setResizable(false);
            tListaVentas.getColumnModel().getColumn(2).setPreferredWidth(330);
            tListaVentas.getColumnModel().getColumn(3).setResizable(false);
            tListaVentas.getColumnModel().getColumn(3).setPreferredWidth(79);
        }

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        EliminarVenta.setText("Eliminar");
        EliminarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarVentaActionPerformed(evt);
            }
        });

        VerDetalle.setText("Ver Detalle");
        VerDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerDetalleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(3, 3, 3)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EliminarVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VerDetalle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(EliminarVenta)
                    .addComponent(VerDetalle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbUsuariosActionPerformed
      
      borrarFilas();
            cargaTablaxUsuario();
         VerDetalle.setEnabled(false);
    }//GEN-LAST:event_jcbUsuariosActionPerformed

    private void EliminarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarVentaActionPerformed
       int idVenta= Integer.parseInt(tListaVentas.getValueAt(tListaVentas.getSelectedRow(),0).toString());
        vData.eliminarVenta(idVenta);
        borrarFilas();
            cargaTablaxUsuario();
            VerDetalle.setEnabled(false);
    }//GEN-LAST:event_EliminarVentaActionPerformed

    private void VerDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerDetalleActionPerformed
        int sel=tListaVentas.getSelectedRowCount();
          if (sel==1) {
           int id= Integer.parseInt(tListaVentas.getValueAt(tListaVentas.getSelectedRow(),0).toString());
            
            
            VerDetalle verDetalle = null;
            try {
                verDetalle = new VerDetalle(id);
            } catch (SQLException ex) {
                Logger.getLogger(PorUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }

        
         jDesktopPaneMenu.add(verDetalle);
        verDetalle.setVisible(true); 
        }else{
              JOptionPane.showMessageDialog(rootPane,"Seleccione solo una fila para ver su detalle");
              
          }

    }//GEN-LAST:event_VerDetalleActionPerformed

    private void tListaVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tListaVentasMouseClicked
         VerDetalle.setEnabled(true);
    }//GEN-LAST:event_tListaVentasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarVenta;
    private javax.swing.JButton VerDetalle;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Usuario> jcbUsuarios;
    private javax.swing.JTable tListaVentas;
    // End of variables declaration//GEN-END:variables

public void cargaCombo(){
    
    for (Usuario usuario : usuarios) {
        jcbUsuarios.addItem(usuario);
    }
    
    usuarios.clear();
}

public void cabecera(){
    
    modelo.addColumn("id Venta");
        modelo.addColumn("idCliente");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Nombre producto");
        modelo.addColumn("Fecha de venta");
    tListaVentas.setModel(modelo);
    
}

public void cargaTablaxUsuario(){
    Usuario user= (Usuario)jcbUsuarios.getSelectedItem();
    
    vData.ventasPorUsuario(user.getIdUsuario());

        for (Venta venta : ventas) {
          DetalleVenta dv=dvData.detallarVenta(venta.getIdVenta());
          Producto prod= pData.buscarPorId(dv.getIdProducto());
           LocalDate fecha=venta.getFechaVenta();
            String fechaOk=fecha.format(dateTimeFormatter);
                modelo.addRow(new Object[]{
                    venta.getIdVenta(),
                    venta.getIdCliente(),
                    dv.getCantidad(),
                    prod.getNombreProducto(),
                    fechaOk
                });
            
        }

        ventas.clear();
    
    
}

 public void borrarFilas() {
        int f = (tListaVentas.getRowCount() - 1);
        for (; f >= 0; f--) {
            modelo.removeRow(f);
        }
    }
}
