/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.ReporteDeVentas;

import AccesoADatos.DetalleVentaData;
import AccesoADatos.ProductoData;
import AccesoADatos.UsuarioData;
import static AccesoADatos.UsuarioData.usuarios;
import AccesoADatos.VentaData;
import static AccesoADatos.VentaData.ventas;
import Entidades.DetalleVenta;
import Entidades.Producto;
import Entidades.Usuario;
import Entidades.Venta;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gaming
 */
public class PorUsuario extends javax.swing.JInternalFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    UsuarioData uData = new UsuarioData();
    VentaData vData = new VentaData();
    DetalleVentaData dvData = new DetalleVentaData();
    ProductoData pData = new ProductoData();
    
    public PorUsuario() {
        initComponents();
        cabecera();
        uData.listarUsuarios();
        cargaCombo();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jcbUsuarios = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tVentas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setTitle("Ventas por usuario");

        jLabel2.setText("Seleccione un usuario");

        jcbUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbUsuariosActionPerformed(evt);
            }
        });

        tVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tVentas);
        if (tVentas.getColumnModel().getColumnCount() > 0) {
            tVentas.getColumnModel().getColumn(0).setResizable(false);
            tVentas.getColumnModel().getColumn(0).setPreferredWidth(50);
            tVentas.getColumnModel().getColumn(1).setResizable(false);
            tVentas.getColumnModel().getColumn(1).setPreferredWidth(50);
            tVentas.getColumnModel().getColumn(2).setResizable(false);
            tVentas.getColumnModel().getColumn(2).setPreferredWidth(330);
            tVentas.getColumnModel().getColumn(3).setResizable(false);
            tVentas.getColumnModel().getColumn(3).setPreferredWidth(79);
        }

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jcbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbUsuariosActionPerformed
      
      borrarFilas();
            cargaTablaxUsuario();
         
    }//GEN-LAST:event_jcbUsuariosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Usuario> jcbUsuarios;
    private javax.swing.JTable tVentas;
    // End of variables declaration//GEN-END:variables

public void cargaCombo(){
    
    for (Usuario usuario : usuarios) {
        jcbUsuarios.addItem(usuario);
    }
    
    usuarios.clear();
}

public void cabecera(){
    
    modelo.addColumn("id Venta");
        modelo.addColumn("idCliente");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Nombre producto");
        modelo.addColumn("Fecha de venta");
    tVentas.setModel(modelo);
    
}

public void cargaTablaxUsuario(){
    Usuario user= (Usuario)jcbUsuarios.getSelectedItem();
    
    vData.ventasPorUsuario(user.getIdUsuario());

        for (Venta venta : ventas) {
          DetalleVenta dv=dvData.detallarVenta(venta.getIdVenta());
          Producto prod= pData.buscarPorId(dv.getIdProducto());
           
                modelo.addRow(new Object[]{
                    venta.getIdVenta(),
                    venta.getIdCliente(),
                    dv.getCantidad(),
                    prod.getNombreProducto(),
                    venta.getFechaVenta(),
                });
            
        }

        ventas.clear();
    
    
}

 public void borrarFilas() {
        int f = (tVentas.getRowCount() - 1);
        for (; f >= 0; f--) {
            modelo.removeRow(f);
        }
    }
}
