/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.ReporteDeVentas;

import AccesoADatos.DetalleVentaData;
import static AccesoADatos.DetalleVentaData.detalles;
import AccesoADatos.ProductoData;
import AccesoADatos.UsuarioData;
import static AccesoADatos.UsuarioData.usuarios;
import AccesoADatos.VentaData;
import static AccesoADatos.VentaData.ventas;
import Entidades.DetalleVenta;
import Entidades.Producto;
import Entidades.Usuario;
import Entidades.Venta;
import static Vista.JfrMenu1.jDesktopPaneMenu;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gaming
 */
public class PorUsuario extends javax.swing.JInternalFrame {

    DefaultTableModel modelo = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int f, int c) {
        return false;
    }
    };
    UsuarioData uData;
    VentaData vData;
    DetalleVentaData dvData;
    ProductoData pData;
    DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    
    public PorUsuario() throws SQLException {
        this.pData = new ProductoData();
        this.dvData = new DetalleVentaData();
        this.vData = new VentaData();
        this.uData = new UsuarioData();
        initComponents();
        cabecera();
        uData.listarUsuarios();
        cargaCombo();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jcbUsuarios = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tListaVentas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        EliminarVenta = new javax.swing.JButton();
        VerDetalle = new javax.swing.JButton();

        setClosable(true);
        setTitle("Ventas por usuario");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(94, 45, 45));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Seleccione un usuario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, 160, 20));

        jcbUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(jcbUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 6, 290, -1));

        tListaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Nombre producto", "Fecha venta"
            }
        ));
        tListaVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tListaVentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tListaVentas);
        if (tListaVentas.getColumnModel().getColumnCount() > 0) {
            tListaVentas.getColumnModel().getColumn(0).setResizable(false);
            tListaVentas.getColumnModel().getColumn(0).setPreferredWidth(50);
            tListaVentas.getColumnModel().getColumn(1).setResizable(false);
            tListaVentas.getColumnModel().getColumn(1).setPreferredWidth(50);
            tListaVentas.getColumnModel().getColumn(2).setResizable(false);
            tListaVentas.getColumnModel().getColumn(2).setPreferredWidth(330);
            tListaVentas.getColumnModel().getColumn(3).setResizable(false);
            tListaVentas.getColumnModel().getColumn(3).setPreferredWidth(79);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 38, -1, 157));

        jButton1.setBackground(new java.awt.Color(102, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 213, 80, 25));

        EliminarVenta.setBackground(new java.awt.Color(102, 0, 0));
        EliminarVenta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EliminarVenta.setForeground(new java.awt.Color(255, 255, 255));
        EliminarVenta.setText("Eliminar");
        EliminarVenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EliminarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarVentaActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 213, 80, 25));

        VerDetalle.setBackground(new java.awt.Color(204, 255, 255));
        VerDetalle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        VerDetalle.setText("Ver Detalle");
        VerDetalle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        VerDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerDetalleActionPerformed(evt);
            }
        });
        jPanel1.add(VerDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 213, 90, 25));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 472, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbUsuariosActionPerformed
      
      borrarFilas();
            cargaTablaxUsuario();
         VerDetalle.setEnabled(false);
    }//GEN-LAST:event_jcbUsuariosActionPerformed

    private void EliminarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarVentaActionPerformed
       int idVenta= Integer.parseInt(tListaVentas.getValueAt(tListaVentas.getSelectedRow(),0).toString());
        vData.eliminarVenta(idVenta);
        borrarFilas();
            cargaTablaxUsuario();
            VerDetalle.setEnabled(false);
    }//GEN-LAST:event_EliminarVentaActionPerformed

    private void VerDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerDetalleActionPerformed
        int sel=tListaVentas.getSelectedRowCount();
          if (sel==1) {
           int id= Integer.parseInt(tListaVentas.getValueAt(tListaVentas.getSelectedRow(),1).toString());
            
            
            VerDetalle verDetalle = null;
            try {
                verDetalle = new VerDetalle(id);
            } catch (SQLException ex) {
                Logger.getLogger(PorUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }

        
         jDesktopPaneMenu.add(verDetalle);
        verDetalle.setVisible(true); 
        }else{
              JOptionPane.showMessageDialog(rootPane,"Seleccione solo una fila para ver su detalle");
              
          }

    }//GEN-LAST:event_VerDetalleActionPerformed

    private void tListaVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tListaVentasMouseClicked
         VerDetalle.setEnabled(true);
    }//GEN-LAST:event_tListaVentasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarVenta;
    private javax.swing.JButton VerDetalle;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Usuario> jcbUsuarios;
    private javax.swing.JTable tListaVentas;
    // End of variables declaration//GEN-END:variables

public void cargaCombo(){
    
    for (Usuario usuario : usuarios) {
        jcbUsuarios.addItem(usuario);
    }
    
    usuarios.clear();
}

public void cabecera(){
    
    modelo.addColumn("id Venta");
    modelo.addColumn("Nº Detalle");
        modelo.addColumn("idCliente");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Nombre producto");
        modelo.addColumn("Fecha de venta");
    tListaVentas.setModel(modelo);
    
}

public void cargaTablaxUsuario(){
    Usuario user= (Usuario)jcbUsuarios.getSelectedItem();
    
    vData.ventasPorUsuario(user.getIdUsuario());

        for (Venta venta : ventas) {
           dvData.detalles(venta.getIdVenta());
             LocalDate fecha=venta.getFechaVenta();
            String fechaOk=fecha.format(dateTimeFormatter);
            
            for (DetalleVenta detalle : detalles) {
            Producto prod=pData.buscarPorId(detalle.getIdProducto());
                modelo.addRow(new Object[]{
                venta.getIdVenta(),
                    detalle.getIdDetalleVenta(),
                venta.getIdCliente(),
                detalle.getIdDetalleVenta(),    
                detalle.getCantidad(),
               prod.getNombreProducto(),
                fechaOk,
                
                });
            }
           
            detalles.clear();
        }
        ventas.clear();
    
    
}

 public void borrarFilas() {
        int f = (tListaVentas.getRowCount() - 1);
        for (; f >= 0; f--) {
            modelo.removeRow(f);
        }
    }
}
