/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.ReporteDeVentas;

import AccesoADatos.DetalleVentaData;
import AccesoADatos.ProductoData;
import AccesoADatos.UsuarioData;
import AccesoADatos.VentaData;
import Entidades.DetalleVenta;
import Entidades.Producto;
import Entidades.Usuario;
import Entidades.Venta;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Gaming
 */
public class VerDetalle extends javax.swing.JInternalFrame {

    int id;
    
     DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    Producto prod = new Producto();
    VentaData vData;
    DetalleVentaData dvData;
    ProductoData pData;
    UsuarioData uData;
    
    public VerDetalle(int id) throws SQLException {
        this.uData = new UsuarioData();
        this.pData = new ProductoData();
        this.dvData = new DetalleVentaData();
        this.vData = new VentaData();
        this.id=id;
        initComponents();
        seteo();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tIdProd = new javax.swing.JTextField();
        tCant = new javax.swing.JTextField();
        tNombreProd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDescProd = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        tFechaV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tUser = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tPUnit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tPtotal = new javax.swing.JTextField();
        Titulo = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tDescuento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tSubtotal = new javax.swing.JTextField();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("id Producto:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 56, 130, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Cantidad:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 102, 130, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 56, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Descripcion:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 102, 90, -1));

        tIdProd.setEditable(false);
        jPanel1.add(tIdProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 49, 30));

        tCant.setEditable(false);
        jPanel1.add(tCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 96, 49, 30));

        tNombreProd.setEditable(false);
        jPanel1.add(tNombreProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 50, 223, -1));

        jScrollPane1.setEnabled(false);

        tDescProd.setEditable(false);
        tDescProd.setColumns(20);
        tDescProd.setRows(5);
        jScrollPane1.setViewportView(tDescProd);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 96, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Fecha de venta:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 240, 130, 20));

        tFechaV.setEditable(false);
        jPanel1.add(tFechaV, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 234, 90, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("id/ Usuario:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 286, 130, 20));

        tUser.setEditable(false);
        jPanel1.add(tUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 199, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Precio unitario:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 148, 130, 20));

        tPUnit.setEditable(false);
        jPanel1.add(tPUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 142, 90, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Precio Total:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 292, 90, -1));

        tPtotal.setEditable(false);
        jPanel1.add(tPtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 286, 125, 30));

        Titulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 102));
        Titulo.setText("Detalle de Venta Nº ");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 6, -1, -1));

        Salir.setBackground(new java.awt.Color(153, 0, 0));
        Salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 335, 80, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Descuento:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 234, 90, -1));

        tDescuento.setEditable(false);
        jPanel1.add(tDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 228, 125, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Subtotal:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 194, 130, 20));

        tSubtotal.setEditable(false);
        jPanel1.add(tSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 188, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 392));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
       this.dispose();
    }//GEN-LAST:event_SalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tCant;
    private javax.swing.JTextArea tDescProd;
    private javax.swing.JTextField tDescuento;
    private javax.swing.JTextField tFechaV;
    private javax.swing.JTextField tIdProd;
    private javax.swing.JTextField tNombreProd;
    private javax.swing.JTextField tPUnit;
    private javax.swing.JTextField tPtotal;
    private javax.swing.JTextField tSubtotal;
    private javax.swing.JTextField tUser;
    // End of variables declaration//GEN-END:variables

public void seteo(){
    
    Titulo.setText("Detalle de la venta Nº "+id);
   
    
    DetalleVenta dv = dvData.detallarVenta(id);
    System.out.println(dv.toString());
     Venta v = vData.buscarVenta(dv.getIdVenta());
     int idUser=v.getIdUsuario();
    Usuario u = uData.buscarUsuario(idUser);
    System.out.println(v.toString());
    prod = pData.buscarPorId(dv.getIdProducto());
    System.out.println(prod.toString());
    LocalDate fecha=v.getFechaVenta();
   String fechaOk = fecha.format(dateTimeFormatter); 
   
    tIdProd.setText(prod.getIdProducto() + "");  //id producto
    tNombreProd.setText(prod.getNombreProducto() + "");  //Nombre prod
    tPUnit.setText(prod.getPrecioActual() + "");    //  Precio unitario
    tDescProd.setText(prod.getDescripcion() + "");  //Descripcion
    tCant.setText(dv.getCantidad() + "");   //Cantidad
    tFechaV.setText(fechaOk);    //Fecha de venta
    tSubtotal.setText((prod.getPrecioActual()*dv.getCantidad()+""));
    tDescuento.setText((dv.getDescuento()+""));
    tUser.setText(v.getIdUsuario()+" - "+u.getApellido()+", "+u.getNombre());  //Usuario-Vendedor
    tPtotal.setText((prod.getPrecioActual()*dv.getCantidad()-dv.getDescuento()+""));     //Precio total

    
}

}
