/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import AccesoADatos.UsuarioData;
import static AccesoADatos.UsuarioData.usuarios;
import Entidades.Usuario;
import static Vista.JfrMenu1.jDesktopPaneMenu;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Gaming
 */
public class GestionUsuario extends javax.swing.JInternalFrame {

    UsuarioData uData;
    /**
     * Creates new form GestionUsuario
     */
    public GestionUsuario() throws SQLException {
        this.uData = new UsuarioData();
        initComponents();
         
         cargaCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbUsuarios = new javax.swing.JComboBox<>();
        bEliminar = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        jLabel3_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestion de Usuarios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccione un usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 160, -1));

        jcbUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(jcbUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 55, 260, -1));

        bEliminar.setBackground(new java.awt.Color(204, 0, 0));
        bEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bEliminar.setForeground(new java.awt.Color(255, 255, 255));
        bEliminar.setText("Eliminar");
        bEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(bEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 80, 28));

        bModificar.setBackground(new java.awt.Color(0, 153, 51));
        bModificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bModificar.setText("Modificar");
        bModificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });
        getContentPane().add(bModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 80, 28));

        bSalir.setBackground(new java.awt.Color(153, 204, 255));
        bSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bSalir.setText("Salir");
        bSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });
        getContentPane().add(bSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 80, 28));

        jLabel3_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel3_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 490, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbUsuariosActionPerformed
       
    }//GEN-LAST:event_jcbUsuariosActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        Usuario u=(Usuario)jcbUsuarios.getSelectedItem();
        ModificarUsuario mUsuario =null;
        try {
         mUsuario =   new ModificarUsuario(u);
         this.dispose();
        } catch (Exception e) {
        }

        jDesktopPaneMenu.add(mUsuario);
        
        mUsuario.setVisible(true);
    }//GEN-LAST:event_bModificarActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
      this.dispose();
    }//GEN-LAST:event_bSalirActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
       
        Usuario u=(Usuario)jcbUsuarios.getSelectedItem();
       int returnValue = 0;
    	returnValue = JOptionPane.showConfirmDialog(null, "Eliminar usuario?", "Confirme la eliminacion de usuario ",JOptionPane.YES_NO_OPTION);
    		
    	if (returnValue == JOptionPane.YES_OPTION)
    		 uData.eliminarUsuario(u.getIdUsuario());
        
    	else if (returnValue == JOptionPane.NO_OPTION)
    		JOptionPane.showMessageDialog(null, "No se elimino el usuario");
       
        cargaCombo();
        
    }//GEN-LAST:event_bEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bModificar;
    private javax.swing.JButton bSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3_wallpaper;
    private javax.swing.JComboBox<Usuario> jcbUsuarios;
    // End of variables declaration//GEN-END:variables

public void cargaCombo(){
    uData.listarUsuarios();
    jcbUsuarios.removeAllItems();
    for (Usuario usuario : usuarios) {
        jcbUsuarios.addItem(usuario);
    }
    usuarios.clear();
}



}
