
package Vista;

import AccesoADatos.Conexion;
import AccesoADatos.UsuarioData;
import Entidades.Usuario;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author chexs
 */
public class JfrmLogin extends javax.swing.JFrame {

    
    static Usuario usuario = new Usuario();
    String ApellUsuario;
    int idUsuarioReg ;
    
    public JfrmLogin() throws SQLException {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Login -MENU DE VENTAS");
        this.setSize(new Dimension (700, 500));
        
        jpPassword.setVisible(true);
        jTextField_PassVisible.setVisible(false);
               
    }
    @Override
    public Image getIconImage(){
        
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imag/ventas.png"));
        return retValue;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtUsuario = new javax.swing.JTextField();
        jpPassword = new javax.swing.JPasswordField();
        jbIniciarSesion = new javax.swing.JButton();
        jCheckBox_Mostrar_cont = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jTextField_PassVisible = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setFocusable(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion de Ventas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 94, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 153));
        jLabel3.setText("Arg Programa / ULP");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 480, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/carrito1.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 173, 136, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 500));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 500));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/user1.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 31, 136, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/user2.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 220, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/password.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 292, -1, -1));

        jtUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtUsuarioKeyPressed(evt);
            }
        });
        jPanel2.add(jtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 217, 176, 35));

        jpPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jpPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpPasswordKeyPressed(evt);
            }
        });
        jPanel2.add(jpPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 289, 176, 35));

        jbIniciarSesion.setBackground(new java.awt.Color(51, 153, 255));
        jbIniciarSesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jbIniciarSesion.setText("Iniciar Sesión");
        jbIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIniciarSesionActionPerformed(evt);
            }
        });
        jPanel2.add(jbIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 375, 176, 37));

        jCheckBox_Mostrar_cont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_Mostrar_contMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCheckBox_Mostrar_contMouseReleased(evt);
            }
        });
        jPanel2.add(jCheckBox_Mostrar_cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 300, 20, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Mostrar");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 320, -1, -1));

        jTextField_PassVisible.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(jTextField_PassVisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 289, 176, 35));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 350, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIniciarSesionActionPerformed
        
        try {
            this.Login();
        } catch (SQLException ex) {
            System.out.println("Error " + ex);
        }
        
    }//GEN-LAST:event_jbIniciarSesionActionPerformed

    private void jtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtUsuarioKeyPressed
        //Al ingresar usuario y apretar enter salta al casillero del Password
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jpPassword.requestFocus();
        }
    }//GEN-LAST:event_jtUsuarioKeyPressed

    private void jpPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpPasswordKeyPressed
        
        if (evt.getKeyCode() == evt.VK_ENTER) {
            try {
                this.Login();
            } catch (SQLException ex) {
                System.out.println("Error " + ex);
            }
        }
    }//GEN-LAST:event_jpPasswordKeyPressed

    private void jCheckBox_Mostrar_contMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_Mostrar_contMouseClicked
        
        if (jCheckBox_Mostrar_cont.isSelected() == true){
        
            String psw = "";
            char[] pswIngresado = jpPassword.getPassword();
            
            for (int i = 0; i < pswIngresado.length; i++){
                psw += pswIngresado[i];
            }
            jTextField_PassVisible.setText(psw);
            jpPassword.setVisible(false);
            jTextField_PassVisible.setVisible(true);
        } else {
            String pswIng = jTextField_PassVisible.getText().trim();
            jpPassword.setText(pswIng);
            jpPassword.setVisible(true);
            jTextField_PassVisible.setVisible(false);
        }
        
    }//GEN-LAST:event_jCheckBox_Mostrar_contMouseClicked

    private void jCheckBox_Mostrar_contMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_Mostrar_contMouseReleased
        
        
    }//GEN-LAST:event_jCheckBox_Mostrar_contMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JfrmLogin().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(JfrmLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox_Mostrar_cont;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField_PassVisible;
    private javax.swing.JButton jbIniciarSesion;
    private javax.swing.JPasswordField jpPassword;
    private javax.swing.JTextField jtUsuario;
    // End of variables declaration//GEN-END:variables

    public void Login() throws SQLException{
        
        if (!jtUsuario.getText().isEmpty() && !jpPassword.getText().isEmpty() ) {
            
            UsuarioData usuario_data = new UsuarioData();           
            
                     
            usuario.setApellido(jtUsuario.getText().trim());
            usuario.setPassword(jpPassword.getText().trim());
            //loginUsuario metodo en UsuarioData
            if (usuario_data.loginUsuario(usuario)) {
                
                //JOptionPane.showMessageDialog(null, "Login Correcto...");
                JfrMenu1 menu = new JfrMenu1();
                menu.setVisible(true);
                menu.repaint();
                
                this.dispose();
                
            } else {
            
                JOptionPane.showMessageDialog(null, "Usuario o Clave Incorrecto");
                
            }
            
        } else {
            
            JOptionPane.showMessageDialog(null, "Ingrese Usuario Y Clave");
            
        }
    
    }
    
    public void ObtenerDdatosDeUsuarioReg() throws SQLException {
        idUsuarioReg = 0;
        ApellUsuario = "";
        UsuarioData uData = new UsuarioData();
        Usuario u = uData.buscarPorPassword(usuario.getPassword());
        if (u!= null ){
            idUsuarioReg = u.getIdUsuario();
            ApellUsuario= u.getApellido();
            usuario.setIdUsuario(idUsuarioReg);
            usuario.setApellido(ApellUsuario);
            
        }
         
        
    }

}
