/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import AccesoADatos.ClienteData;
import Entidades.Cliente;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author chexs
 */
public class JInternalCliente extends javax.swing.JInternalFrame {

    
    int otener_idCliente = 0;
    
    public JInternalCliente() {
        initComponents();
        this.setSize(new Dimension(400, 350));
        this.setTitle("Nuevo Cliente");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxt_domicilio = new javax.swing.JTextField();
        jtxt_apellido = new javax.swing.JTextField();
        jtxt_telefono = new javax.swing.JTextField();
        jtxt_nombre = new javax.swing.JTextField();
        jbutton_guardar = new javax.swing.JButton();
        jLabel_imgFondo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Nuevo Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 25, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 80, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 80, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Domicilio:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Teléfono:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 80, -1));

        jtxt_domicilio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jtxt_domicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 155, 190, -1));

        jtxt_apellido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jtxt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 115, 190, -1));

        jtxt_telefono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jtxt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 195, 190, -1));

        jtxt_nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jtxt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 75, 190, -1));

        jbutton_guardar.setBackground(new java.awt.Color(0, 153, 153));
        jbutton_guardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbutton_guardar.setForeground(new java.awt.Color(51, 51, 51));
        jbutton_guardar.setText("Guardar");
        jbutton_guardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbutton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(jbutton_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 95, 35));

        jLabel_imgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel_imgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_guardarActionPerformed
        
        Cliente cliente = new Cliente();
        ClienteData clienteData = new ClienteData();
        
        if ( jtxt_nombre.getText().equals("") || jtxt_apellido.getText().equals("") || 
                jtxt_domicilio.getText().equals("") || jtxt_telefono.getText().equals("")) {
            
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
            
            jtxt_nombre.setBackground(Color.RED);
            
        } else {
            
            if ( !clienteData) {
                
            }
        
        }
        
    }//GEN-LAST:event_jbutton_guardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_imgFondo;
    private javax.swing.JButton jbutton_guardar;
    private javax.swing.JTextField jtxt_apellido;
    private javax.swing.JTextField jtxt_domicilio;
    private javax.swing.JTextField jtxt_nombre;
    private javax.swing.JTextField jtxt_telefono;
    // End of variables declaration//GEN-END:variables
}
