package Vista;

import AccesoADatos.ClienteData;
import Entidades.Cliente;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sergio Mendez
 */
public class JInternalGestioCliente extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };
    
    ClienteData cData;
    private int idCliente = 0;

    public JInternalGestioCliente() throws SQLException {
        this.cData = new ClienteData();
        
        initComponents();

        this.setSize(new Dimension(900, 400));
        this.setTitle("Gestion Cliente");

        this.encabezadoTabla();
        this.llenarTablaCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_cliente = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton_actualizar = new javax.swing.JButton();
        jButton_Eliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxt_telefono = new javax.swing.JTextField();
        jtxt_direccion = new javax.swing.JTextField();
        jtxt_dni = new javax.swing.JTextField();
        jtxt_apellido = new javax.swing.JTextField();
        jtxt_nombre = new javax.swing.JTextField();
        jLabel1_Wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestion Clientes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 15, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(153, 153, 153));

        jTable_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_cliente);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 3, 656, 260));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, 660, 265));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_actualizar.setBackground(new java.awt.Color(51, 204, 0));
        jButton_actualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_actualizar.setText("Actualizar");
        jButton_actualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 30));

        jButton_Eliminar.setBackground(new java.awt.Color(255, 51, 51));
        jButton_Eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Eliminar.setText("Eliminar");
        jButton_Eliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 55, 145, 90));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 7, 85, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Apellido:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 40, 85, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Dni:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 70, 85, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Direccion:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 100, 85, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Telefono:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 130, 85, -1));
        jPanel3.add(jtxt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 125, 105, 30));
        jPanel3.add(jtxt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 95, 105, 30));
        jPanel3.add(jtxt_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 65, 105, 30));
        jPanel3.add(jtxt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 33, 105, 30));
        jPanel3.add(jtxt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 3, 105, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 200, 160));

        jLabel1_Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imag/Fondo black.jpeg"))); // NOI18N
        getContentPane().add(jLabel1_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed

        if (jtxt_apellido.getText().isEmpty() && jtxt_nombre.getText().isEmpty() && jtxt_dni.getText().isEmpty()
                && jtxt_direccion.getText().isEmpty() && jtxt_telefono.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "¡Complete los campos!");
        } else {
            Cliente c = new Cliente();
            c.setApellido(jtxt_apellido.getText().trim());
            c.setNombre(jtxt_nombre.getText().trim());
            c.setDni(Integer.parseInt(jtxt_dni.getText().trim()));
            c.setDomicilio(jtxt_direccion.getText().trim());
            c.setTelefono(Integer.parseInt(jtxt_telefono.getText().trim()));

            if (cData.actualizarDatoCliente(c, idCliente)) {
                JOptionPane.showMessageDialog(null, "Datos Actualizados");
                this.borrarFilas();
                this.llenarTablaCliente();
                this.limpiarTxt();
            } else {
                JOptionPane.showMessageDialog(null, "Error al Actualizar");
            }
        }

    }//GEN-LAST:event_jButton_actualizarActionPerformed

    private void jButton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarActionPerformed
        if (idCliente == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un Cliente");
        } else {
            if (cData.bajaDeCliente2(idCliente)) {
                JOptionPane.showMessageDialog(null, "Cliente Eliminado del Sistema");
                this.borrarFilas();
                this.llenarTablaCliente();
                this.limpiarTxt();
            } else {
                JOptionPane.showMessageDialog(null, "Error al Eliminar Cliente");
                this.limpiarTxt();
            }
        }
    }//GEN-LAST:event_jButton_EliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Eliminar;
    private javax.swing.JButton jButton_actualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_Wallpaper;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_cliente;
    private javax.swing.JTextField jtxt_apellido;
    private javax.swing.JTextField jtxt_direccion;
    private javax.swing.JTextField jtxt_dni;
    private javax.swing.JTextField jtxt_nombre;
    private javax.swing.JTextField jtxt_telefono;
    // End of variables declaration//GEN-END:variables

    private void limpiarTxt() {
        jtxt_apellido.setText("");
        jtxt_nombre.setText("");
        jtxt_dni.setText("");
        jtxt_direccion.setText("");
        jtxt_telefono.setText("");
    }

    private void encabezadoTabla() {
        ArrayList<Object> encabezado = new ArrayList<>();
        encabezado.add("ID");
        encabezado.add("Nombre");
        encabezado.add("Apellido");
        encabezado.add("Dni");
        encabezado.add("Domicílio");
        encabezado.add("Telefono");

        for (Object col : encabezado) {
            modelo.addColumn(col);
        }
        this.jTable_cliente.setModel(modelo);
    }
    
    private void borrarFilas() {
        int filas = jTable_cliente.getRowCount() - 1;
        for (int i = filas; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

    private void llenarTablaCliente() {
        List<Cliente> clientes = cData.listaClientes();

        for (Cliente cliente: clientes) {
            modelo.addRow(new Object[]{
                cliente.getIdCliente(),
                cliente.getNombre(),
                cliente.getApellido(),
                cliente.getDni(),
                cliente.getDomicilio(),
                cliente.getTelefono(),
            });
        }

        jTable_cliente.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_p = jTable_cliente.rowAtPoint(e.getPoint());
                int columna_p = 0;

                if (fila_p > -1) {
                    idCliente = (int) modelo.getValueAt(fila_p, columna_p);
                    datosSeleccionados(idCliente);
                }
            }
        });
    }

    private void datosSeleccionados(int idCliente) {
        Cliente cliente = cData.buscarClienteXid(idCliente);

        jtxt_apellido.setText(cliente.getApellido());
        jtxt_nombre.setText(cliente.getNombre());                
        jtxt_dni.setText(String.valueOf(cliente.getDni()));
        jtxt_direccion.setText(cliente.getDomicilio());
        jtxt_telefono.setText(String.valueOf(cliente.getTelefono()));
    }
}
