/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import AccesoADatos.UsuarioData;
import Entidades.Usuario;
import java.awt.Color;
import static java.awt.Event.ENTER;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Gaming
 */
public class NuevoUsuario extends javax.swing.JInternalFrame {

    Usuario user = new Usuario();
    UsuarioData uData;

    /**
     * Creates new form NuevoUsuario
     */
    public NuevoUsuario() throws SQLException {
        this.uData = new UsuarioData();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tApellido = new javax.swing.JTextField();
        tNombre = new javax.swing.JTextField();
        bSalir = new javax.swing.JButton();
        bGuardar = new javax.swing.JButton();
        bNuevo = new javax.swing.JButton();
        tPass = new javax.swing.JPasswordField();
        tCpass = new javax.swing.JPasswordField();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(26, 56, 48));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nuevo Usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 8, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Apellido");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 54, 135, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 135, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Contraseña");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 146, 135, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Confirme contraseña");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 192, 135, -1));

        tApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tApellidoKeyPressed(evt);
            }
        });
        jPanel1.add(tApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 48, 170, 28));

        tNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tNombreKeyPressed(evt);
            }
        });
        jPanel1.add(tNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 94, 170, 28));

        bSalir.setBackground(new java.awt.Color(153, 0, 0));
        bSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bSalir.setForeground(new java.awt.Color(255, 255, 255));
        bSalir.setText("Salir");
        bSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });
        jPanel1.add(bSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 80, 30));

        bGuardar.setBackground(new java.awt.Color(51, 153, 0));
        bGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bGuardar.setText("Guardar");
        bGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(bGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 80, 30));

        bNuevo.setBackground(new java.awt.Color(153, 255, 255));
        bNuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bNuevo.setText("Nuevo");
        bNuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(bNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 80, 30));

        tPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tPassKeyPressed(evt);
            }
        });
        jPanel1.add(tPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 170, 28));

        tCpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tCpassKeyPressed(evt);
            }
        });
        jPanel1.add(tCpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 186, 170, 28));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevoActionPerformed
        limpiar();
    }//GEN-LAST:event_bNuevoActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed

        guardar();

    }//GEN-LAST:event_bGuardarActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_bSalirActionPerformed

    private void tApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tApellidoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            tNombre.requestFocus();
        }
    }//GEN-LAST:event_tApellidoKeyPressed

    private void tNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNombreKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            tPass.requestFocus();
        }
    }//GEN-LAST:event_tNombreKeyPressed

    private void tPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tPassKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            tCpass.requestFocus();
            tCpass.selectAll();
        }
    }//GEN-LAST:event_tPassKeyPressed

    private void tCpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCpassKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            guardar();
        }
    }//GEN-LAST:event_tCpassKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bNuevo;
    private javax.swing.JButton bSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tApellido;
    private javax.swing.JPasswordField tCpass;
    private javax.swing.JTextField tNombre;
    private javax.swing.JPasswordField tPass;
    // End of variables declaration//GEN-END:variables

    public void limpiar() {

        tApellido.setText("");
        tNombre.setText("");
        tPass.setText("");
        tCpass.setText("");
        tApellido.setBackground(Color.white);
        tNombre.setBackground(Color.white);
        tPass.setBackground(Color.white);
        tCpass.setBackground(Color.white);

    }

    public boolean guardar() {
        boolean resp = false;
        String apellido = tApellido.getText().trim();
        String nombre = tNombre.getText().trim();
        String pass = tPass.getText().trim();
        String cPass = tCpass.getText().trim();

        if (apellido.isEmpty() || nombre.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Por favor, complete todos los campos");
        } else {
            if (!cPass.equals(pass)) {
                tPass.setBackground(Color.red);
                tCpass.setBackground(Color.red);
                JOptionPane.showMessageDialog(rootPane, "Las contraseñas no coinciden");
                tPass.requestFocus();
                tPass.selectAll();
                tPass.setBackground(Color.white);
                tCpass.setBackground(Color.white);

            } else {
                user.setApellido(apellido);
                user.setNombre(nombre);
                user.setPassword(pass);
                if (uData.buscarUsuario(user.getApellido(), user.getNombre(), user.getPassword()) == false) {
                    JOptionPane.showMessageDialog(rootPane, "El usuario ya se encuentra registrado");

                } else {
                    if (uData.guardarUsuario(user)) {
                        tApellido.setBackground(Color.green);
                        tNombre.setBackground(Color.green);
                        tPass.setBackground(Color.green);
                        tCpass.setBackground(Color.green);
                    }
                }
            }
        }
        return resp;
    }
}
