package Vista.Producto;

import AccesoADatos.ProductoData;
import Entidades.Producto;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class NuevoProducto extends javax.swing.JInternalFrame {

    private ProductoData data;
    private Producto producto = null;

    /**
     * Creates new form NuevoProducto
     */
    public NuevoProducto() throws SQLException {
        this.data = new ProductoData();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitle = new javax.swing.JLabel();
        jbCancelar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbBorrar = new javax.swing.JButton();
        jfStock = new javax.swing.JTextField();
        jfNombre = new javax.swing.JTextField();
        jlDescripcion = new javax.swing.JLabel();
        jlStock = new javax.swing.JLabel();
        jfDescripcion = new javax.swing.JTextField();
        jlNombre = new javax.swing.JLabel();
        jlPrecioActual = new javax.swing.JLabel();
        jfPrecioActual = new javax.swing.JTextField();

        jlTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jlTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitle.setText("Nuevo Producto");
        jlTitle.setToolTipText("");
        jlTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbEditar.setText("Nuevo");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbBorrar.setText("Borrar");
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        jlDescripcion.setText("Descripción");

        jlStock.setText("Stock");

        jlNombre.setText("Nombre");

        jlPrecioActual.setText("Precio actual");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jlTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlPrecioActual, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlStock, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jfPrecioActual, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jfStock, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jbEditar)
                        .addGap(18, 18, 18)
                        .addComponent(jbBorrar)
                        .addGap(18, 18, 18)
                        .addComponent(jbCancelar)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDescripcion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfPrecioActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPrecioActual))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlStock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbEditar)
                    .addComponent(jbBorrar)
                    .addComponent(jbCancelar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        String nombre = jfNombre.getText();
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe completar el nombre del producto.");
            return;
        }

        String descripcion = jfDescripcion.getText();
        if (descripcion.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe completar la descripción del producto.");
            return;
        }

        String precioTexto = jfPrecioActual.getText();
        if (precioTexto.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe completar el precio actual del producto.");
            return;
        }

        float precioActual = 0;
        try {
            precioActual = Float.parseFloat(precioTexto);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "El precio actual debe debe ser un número.");
            return;
        }

        String stockTexto = jfStock.getText();
        if (stockTexto.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe completar el stock del producto.");
            return;
        }

        int stock = 0;
        try {
            stock = Integer.parseInt(stockTexto);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "El stock debe debe ser un número.");
            return;
        }

        if (producto != null) {
            producto.setNombreProducto(nombre);
            producto.setDescripcion(descripcion);
            producto.setPrecioActual(precioActual);
            producto.setStock(stock);
            data.modificarProducto(producto);
        } else {
            Producto nuevoProducto = new Producto(nombre, descripcion, precioActual, stock, true);
            data.nuevoProducto(nuevoProducto);
        }

        if (producto == null) {
            borrarDatos();
        }
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        borrarDatos();
    }//GEN-LAST:event_jbBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JTextField jfDescripcion;
    private javax.swing.JTextField jfNombre;
    private javax.swing.JTextField jfPrecioActual;
    private javax.swing.JTextField jfStock;
    private javax.swing.JLabel jlDescripcion;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlPrecioActual;
    private javax.swing.JLabel jlStock;
    private javax.swing.JLabel jlTitle;
    // End of variables declaration//GEN-END:variables

    
    public void editar(Producto producto) {
        this.producto = producto;
        
        jlTitle.setText("Editar producto");
        jbEditar.setText("Editar");
        jbBorrar.setVisible(false);
        
        jfNombre.setText(producto.getNombreProducto());
        jfDescripcion.setText(producto.getDescripcion());
        jfPrecioActual.setText(producto.getPrecioActual() + "");
        jfStock.setText(producto.getStock() + "");
    }
    
    public void borrarDatos() {
        jfNombre.setText("");
        jfDescripcion.setText("");
        jfPrecioActual.setText("");
        jfStock.setText("");
    }
}
